# Hausaufgabe 3
> *Abgabe bis 17.11.2023 um 23.59*

### Das Runde muss ins Eckige
Ein Fußball wird von einer Spielerin von dem Mittelpunkt der Torlinie in einer parabelförmigen Bahn auf das Tor der Gegner geschossen. Die Funktion, die diesen Schuss beschreibt, wird folgend beschrieben.

- Die Funktion für x-Position lautet: $x(t)=5,25\frac{m}{s}t$.
- Die Funktion für die y-Position lautet: $y(t)=-0,365\frac{m}{s^2}t^2+6.95\frac{m}{s}t$.
- Die Funktion für die z-Position lautet: $z(t)=-0,49\frac{m}{s^2}t^2+9,9\frac{m}{s}t$.
- Das Fußballfeld ist 105 m lang und 64 m breit.
- Die Tore befinden sich an den Enden der längeren Strecke und befinden sich genau in der Mitte der kürzeren Strecke.
- Der Radius des Balls ist der Einfachheit zu vernachlässigen.
- Das (gegnerische) Tor gilt nur als getroffen, wenn sich der Ball auf der Torlinie innerhalb der Innenmaße des Tors befindet.
- Jedes Tor ist innen 2,44 m hoch und 7,32 m breit.
- Das Spielfeld gilt dann als verlassen, wenn der Ball außerhalb der Außenmaße des Spielfeldes ist.
- Wenn die Spielerin, die den Ball schießt, in Richtung gegnerisches Tor schaut, dann hat die Außenecke des Spielfelds zu ihrer Rechten auf Bodenhöhe die Koordinaten ``(0,0,0)``.

Beachtet die Startposition des Balls!

Benutzt zur Lösung aller Aufgaben ```numpy```. Ihr bekommt die Punkte für den korrekten Lösungsweg, nicht für die korrekte Antwort.

In [247]:
import numpy as np
import matplotlib.pyplot as plt

#### a) Vorgegebne Funktionen implementieren *(20 Punkte)*
Implementiert die vorgegebenen Funktionen ``x(t)``, ``y(t)`` und ``z(t)`` und benutzt diese dann, um die Funktion ``f(t)`` zu implementieren, die ``x(t)``, ``y(t)`` und ``z(t)`` in eine Matrix zusammenfasst und die anschließend transponiert. Die Matrix soll am Ende folgende Gestalt haben:
$$M = \begin{pmatrix}x_1 & y_1 & z_1 \\ \vdots & \vdots & \vdots \\ x_n & y_n & z_n\end{pmatrix}$$
Dabei sind $x_1,\dots,x_n$ die Rückgabewerte von ``x(t)``, usw. Es liegen damit n Zeilen und 3 Spalten vor.

In [248]:
start = np.array([-32,0,0])
def x(t):
    x = (t * 5.25)+start[0]
    
    return x

def y(t):
    y = (-0.365 * (t**2) + (6.95 * t))+start[1]

    return y

def z(t):
    z = (-0.49 * (t **2) + 9.9 * t)+start[2]
    return z

def f(t):
    f = np.ones((50,3)) * (np.arange(0,50)/49)[:,None] * 20
    f[:,0,None] = x(f[:,0,None])
    f[:,1,None] = y(f[:,1,None])
    f[:,2,None] = z(f[:,2,None])
    return f

#### b) Funktionen ausführen *(20 Punkte)*
Berechnet insgesamt 50 Positionen des Balls über einen Zeitraum von 20 Sekunden. Diese Samples sollen alle den gleichen zeitlichen Abstand zu einander haben. Speichert diese Positionen in einem numpy Array. 
Nutzt hierfür die Funktion aus a).

In [249]:
positions = [] # TODO
print(f(50))

[[-32.           0.           0.        ]
 [-29.85714286   2.7759267    3.95918367]
 [-27.71428571   5.4302374    7.75510204]
 [-25.57142857   7.96293211  11.3877551 ]
 [-23.42857143  10.37401083  14.85714286]
 [-21.28571429  12.66347355  18.16326531]
 [-19.14285714  14.83132028  21.30612245]
 [-17.          16.87755102  24.28571429]
 [-14.85714286  18.80216576  27.10204082]
 [-12.71428571  20.60516451  29.75510204]
 [-10.57142857  22.28654727  32.24489796]
 [ -8.42857143  23.84631404  34.57142857]
 [ -6.28571429  25.28446481  36.73469388]
 [ -4.14285714  26.60099958  38.73469388]
 [ -2.          27.79591837  40.57142857]
 [  0.14285714  28.86922116  42.24489796]
 [  2.28571429  29.82090796  43.75510204]
 [  4.42857143  30.65097876  45.10204082]
 [  6.57142857  31.35943357  46.28571429]
 [  8.71428571  31.94627239  47.30612245]
 [ 10.85714286  32.41149521  48.16326531]
 [ 13.          32.75510204  48.85714286]
 [ 15.14285714  32.97709288  49.3877551 ]
 [ 17.28571429  33.07746772  49.75

#### c) Daten auswerten I *(20 Punkte)*
Berechnet den höchsten Punkt, den der Ball in euren Samples erreicht. Implementiert dazu die Funktion ```highestPoint```. Gebt auf 2 Dezimalstellen genau an, wie hoch der Ball flog und zu welchem Zeitpunkt diese Höhe erreicht wurde. Eure Ausgabe könnte z.B. so aussehen:

```Der Ball war bei X m an seinem höchsten Punkt. Er erreicht diesen nach Y Sekunden```

Benutzt hierfür die ```print```-Funktion

In [250]:
# Falls ihr a) und b) nicht lösen können, könnt ihr das folgende Array entkommentieren, um dennoch die nachfolgenden Aufgaben bearbeiten zu können.
# Nutzt dieses Array nur in diesem Fall!
# Andernfalls verwendet die Daten weiter, die ihr in a) und b) generiert haben.

# positions = np.array([[0., 34., 0.], [2.24489796, 35.19117035, 4.40649729], [4.48979592, 36.31570179, 8.64639733], [6.73469388, 37.37359434, 12.71970012], [8.97959184, 38.36484798, 16.62640566], [11.2244898, 39.28946272, 20.36651395], [13.46938776, 40.14743857, 23.94002499], [15.71428571, 40.93877551, 27.34693878], [17.95918367, 41.66347355, 30.58725531], [20.20408163, 42.32153269, 33.66097459], [22.44897959, 42.91295294, 36.56809663], [24.69387755, 43.43773428, 39.30862141], [26.93877551, 43.89587672, 41.88254894], [29.18367347, 44.28738026, 44.28987922], [31.42857143, 44.6122449, 46.53061224], [33.67346939, 44.87047064, 48.60474802], [35.91836735, 45.06205748, 50.51228655], [38.16326531, 45.18700541, 52.25322782], [40.40816327, 45.24531445, 53.82757185], [42.65306122, 45.23698459, 55.23531862], [44.89795918, 45.16201583, 56.47646814], [47.14285714, 45.02040816, 57.55102041], [49.3877551, 44.8121616, 58.45897543], [51.63265306, 44.53727613, 59.20033319], [53.87755102, 44.19575177, 59.77509371], [
#    56.12244898, 43.7875885, 60.18325698], [58.36734694, 43.31278634, 60.42482299], [60.6122449, 42.77134527, 60.49979175], [62.85714286, 42.16326531, 60.40816327], [65.10204082, 41.48854644, 60.14993753], [67.34693878, 40.74718867, 59.72511454], [69.59183673, 39.939192, 59.13369429], [71.83673469, 39.06455643, 58.3756768], [74.08163265, 38.12328197, 57.45106206], [76.32653061, 37.1153686, 56.35985006], [78.57142857, 36.04081633, 55.10204082], [80.81632653, 34.89962516, 53.67763432], [83.06122449, 33.69179509, 52.08663057], [85.30612245, 32.41732611, 50.32902957], [87.55102041, 31.07621824, 48.40483132], [89.79591837, 29.66847147, 46.31403582], [92.04081633, 28.1940858, 44.05664307], [94.28571429, 26.65306122, 41.63265306], [96.53061224, 25.04539775, 39.04206581], [98.7755102, 23.37109538, 36.2848813], [101.02040816, 21.6301541, 33.36109954], [103.26530612, 19.82257393, 30.27072053], [105.51020408, 17.94835485, 27.01374427], [107.75510204, 16.00749688, 23.59017076], [110., 14., 20.]])

def highestPoint(positions):
    
    print(f"Der Ball war bei {np.max(f(50)[:,2])} an seinem höchsten Punkt. Er erreicht diesen nach {((np.argmax(f(50)[:,2])+1)/50)*20} Sekunden.")

highestPoint(positions)

Der Ball war bei 50.0 an seinem höchsten Punkt. Er erreicht diesen nach 10.4 Sekunden.


#### d) Daten auswerten II *(20 Punkte)*
Verlässt der Ball zu einem Zeitpunkt seitlich das Spielfeld? Implementiert die Funktion ```leftField```, um diese Frage zu beantworten. Gebt die Antwort in ähnlichem Format wie in c) aus.

In [251]:
def leftField(positions):
    # TODO
    print()

leftField(positions)

#### e) Daten plotten *(20 Punkte)*
Plottet X-, Y- und Z-Achse des Spielfelds und die Schussbahn des Balls in einem dreidimensionalen Diagramm. Achtet auf korrekte Achsenbeschriftung.

In [252]:
X = [np.squeeze(f(50)[:,0])]
Y = [np.squeeze(f(50)[:,1])]
Z = [np.squeeze(f(50)[:,2])]
print(X)
fig = plt.figure()
ax = fig.add_subplot(projection='3d')

ax.plot(X,Y,Z)
plt.show()


[array([-32.        , -29.85714286, -27.71428571, -25.57142857,
       -23.42857143, -21.28571429, -19.14285714, -17.        ,
       -14.85714286, -12.71428571, -10.57142857,  -8.42857143,
        -6.28571429,  -4.14285714,  -2.        ,   0.14285714,
         2.28571429,   4.42857143,   6.57142857,   8.71428571,
        10.85714286,  13.        ,  15.14285714,  17.28571429,
        19.42857143,  21.57142857,  23.71428571,  25.85714286,
        28.        ,  30.14285714,  32.28571429,  34.42857143,
        36.57142857,  38.71428571,  40.85714286,  43.        ,
        45.14285714,  47.28571429,  49.42857143,  51.57142857,
        53.71428571,  55.85714286,  58.        ,  60.14285714,
        62.28571429,  64.42857143,  66.57142857,  68.71428571,
        70.85714286,  73.        ])]


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (50,)  and requested shape (1,)

Error in callback <function _draw_all_if_interactive at 0x118d47240> (for post_execute):


AttributeError: 'Line3D' object has no attribute '_verts3d'

AttributeError: 'Line3D' object has no attribute '_verts3d'

<Figure size 640x480 with 1 Axes>